### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by omgbox** [kdi/media-encoder#1]
> ~/Downloads/media-encoder# nodejs server.js
> { [Error: ENOENT, no such file or directory '/home/nodejs/Downloads/media-encoder/app/models/']
>   errno: 34,
>   code: 'ENOENT',
>   path: '/home/nodejs/Downloads/media-encoder/app/models/',
>   syscall: 'readdir' }
> 
> npm -v 2.5.1
> 
> nodejs -v 0.10.33

**Comment by omgbox** [comment]
> Error: Cannot find module 'html' at Function.Module._resolveFilename (module.js:338:15) at Function.Module._load (module.js:280:25) at Module.require (module.js:364:17) at require (module.js:380:17) at new View (/home/nodejs/Downloads/media-encoder/node_modules/express/lib/view.js:43:49) at Function.app.render (/home/nodejs/Downloads/media-encoder/node_modules/express/lib/application.js:484:12) at ServerResponse.res.render (/home/nodejs/Downloads/media-encoder/node_modules/express/lib/response.js:779:7) at Class.extend.render (/home/nodejs/Downloads/media-encoder/node_modules/brisk/app/controllers/main.js:56:7) at Class.extend.index (/home/nodejs/Downloads/media-encoder/node_modules/brisk/app/controllers/main.js:16:8) at processRequest (/home/nodejs/Downloads/media-encoder/node_modules/brisk/lib/brisk.js:642:9)

**Comment by tracend** [comment]
The first error is trivial - the models folder isn't automatically created: 

```
/home/nodejs/Downloads/media-encoder/app/models/
```

For the second, handlebars seems to not be loading. This should have something to do with [the express config](https://github.com/kdi/media-encoder/blob/55fe7ae1fa6003e9da8436c32f56cbffb5d80e16/config/express.js#L23). Later versions of hsb & brisk might have diverged causing it. 

I'll post a quick update ;)

**Comment by omgbox** [comment]
Understood thanks
